services:
  metasim:
    user: ${DOCKER_UID}:${DOCKER_GID}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${PROXY}
        - https_proxy=${PROXY}
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-1000}
        - DOCKER_USER=${DOCKER_USER:-user}
    container_name: metasim
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}                       # forwarded by VS Code helper
      - QT_X11_NO_MITSHM=1                      # avoid MIT-SHM issues
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
      # VirtualGL: tell it where to do 3D rendering (host GPU X display)environment
      # If your host has a GPU X server on :0, keep this:
      # - VGL_DISPLAY=:0
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - OMNI_KIT_ACCEPT_EULA=YES
      # Forward ssh keys
      - SSH_AUTH_SOCK=/ssh-agent
      # Forward Huggingface keys
      - HF_TOKEN=${HF_TOKEN}
      # Forward LLM keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix           # 2D X path to your local desktop
      - /usr/local/cuda:/usr/local/cuda
      - ./:/home/${DOCKER_USER}/RoboVerse
      # - ${HOME}/.gitconfig:/home/vscode/.gitconfig:ro
      - ${HOME}/.gitconfig:/home/${DOCKER_USER}/.gitconfig:ro
      - ${HOME}/.ssh:/home/${DOCKER_USER}/.ssh:ro
      - "${SSH_AUTH_SOCK:-/tmp/ssh-agent-not-set}:/ssh-agent"
    devices:
      - /dev/dri:/dev/dri                       # expose DRM nodes (helps some stacks)
    tty: true
    ipc: host
    # ports:
    #   - "47995:47995/tcp"   # for LIVESTREAM=1 (native client)
    #   - "49100:49100/tcp"   # for LIVESTREAM=2 (WebRTC)
    #   - "49100:49100/udp"   # (WebRTC media)